### ISSUE TITLE
Work with local dayspan-vuetify package

### ISSUE THREAD

**Issue by bupaev** [ClickerMonkey/dayspan-vuetify-example#1]
Hi Philip! First of all thanks for your amazing work, your library is really great! :sparkles::calendar::sparkles:

I'm trying to adopt your library to some medical scheduler app and it requires a lot of changes, so it's very convenient to do it locally using `npm link` instead of pushing updates to the remote repo and then install the updated package via repo's git link.

But `npm link` approach doesn't work properly for me 😢 
I've tried many variants but let's consider the simple one:
1. Clone `dayspan-vuetify-example` and `dayspan-vuetify`
2. Run `npm install` in both
3. Create npm link
```
cd ~/projects/dayspan-vuetify
npm link
cd ~/projects/dayspan-vuetify-example  
npm link dayspan-vuetify
```
4. Run `npm run build` in `dayspan-vuetify`
5. Run `npm run serve` in  `dayspan-vuetify-example`
6. `dayspan-vuetify-example` is automatically reloaded with updated `dayspan-vuetify` resources

But after that, I have a bunch of type check warnings (I feel it's related to `dayspan` lib) and when I try to create a new event I get `[Vue warn]: Error in render: "TypeError: Cannot read property 'durationUnit' of null"`

You can see on the screenshot
<img width="1657" alt="screen shot 2018-10-13 at 00 51 28" src="https://user-images.githubusercontent.com/1748949/46888414-4300db00-ce82-11e8-8d3c-2776d35d0d9b.png">

So I've spent half a day to resolve this issue but I couldn't :persevere:
I'd be most grateful if you'd help me, maybe you suppose better approach based on your experience of `dayspan-vuetify` local development or just recommend some fix for my way :pray:

NPM 6.4.0
Node 8.11.2
dayspan-vuetify 0.3.2
macOS 10.13.6

**Comment by ClickerMonkey** [comment]
I followed your steps and I'm not seeing any problems :-/

**Comment by bupaev** [comment]
Oh, it's strange :hushed: I have the same issue even in other repo. 
Okay, I'll try to reproduce it on my PC to be sure.

**Comment by bupaev** [comment]
The issue successfully reproduced on Windows machine (Win 10, Node 8.12.0, NPM 6.4.1 )
![image](https://user-images.githubusercontent.com/1748949/46897734-5de54680-cea6-11e8-941d-1567872424ac.png)

Did you start/restart dev server in `dayspan-vuetify-example` after creating npm link? It could be the reason why you didn't see the issue.

**Comment by ClickerMonkey** [comment]
Here's what I ran:

```bash
git clone https://github.com/ClickerMonkey/dayspan-vuetify
git clone https://github.com/ClickerMonkey/dayspan-vuetify-example
cd dayspan-vuetify
npm link # runs install
cd ../dayspan-vuetify-example
npm link dayspan-vuetify
npm install
cd ../dayspan-vuetify
npm run build
cd ../dayspan-vuetify-example
npm run serve
```

**Comment by ClickerMonkey** [comment]
I'm ashamed that I've never heard of `npm link` before - that is going to make things much simpler where I work...

**Comment by bupaev** [comment]
I guess you don't have errors in your scenario because `npm link dayspan-vuetify` is somehow overridden by following `npm install`, so you even don't really link `dayspan-vuetify` to `dayspan-vuetify-example` :disappointed_relieved:

Please run `npm link dayspan-vuetify` at the end of your scenario and you'll see the same errors as shown in my screenshots
```
cd ../dayspan-vuetify-example
npm link dayspan-vuetify
npm run serve
```

**Comment by bupaev** [comment]
I've tried a few solutions, nothing helps :disappointed: 
Could you just describe your own flow to local development of npm packages? How do you avoid publish/install hell when developing two projects locally that depended on each other?

**Comment by bupaev** [comment]
So it seems I've found an appropriate solution. 
It's `Yarn` with [Yalc](https://github.com/whitecolor/yalc) ([nice article](https://medium.com/@mtfranchetto/the-solution-for-a-working-npm-yarn-link-ddcb4f3c785e) on Medium)

How to set it up in short:
```bash
yarn global add yalc
<...>
cd dayspan-vuetify
yalc publish
cd ../dayspan-vuetify-example
yarn
yalc link dayspan-vuetify
```

Then to update `dayspan-vuetify-example` with local changes run this line in `dayspan-vuetify` folder:
```bash
yarn build && yalc push
```

**Comment by ClickerMonkey** [comment]
Good to hear!
